name: CD pipeline

on:
  push:
    branches: [main]
    paths: 
      - '**/*.tf'
      - '**/*.tfvars'
      - '.github/workflows/cd.yml'
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Debug OIDC subject
        run: |
          echo "Repo: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          
      - name: Debug token claims
        run: |
          echo "sub attendu par AWS: repo:mz-kara/zero-trust-web:ref:refs/heads/main"
          echo "repository: ${{ github.repository }}"
          echo "ref: ${{ github.ref }}"
          echo "ref_type: ${{ github.ref_type }}"
          echo "workflow_ref: ${{ github.workflow_ref }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::594161137006:role/oidc-github-role
          aws-region: "eu-west-3"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Format Terraform
        run: terraform fmt
        working-directory: ./terraform/infra

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./terraform/infra

      - name: Init Terraform
        run: terraform init
        working-directory: ./terraform/infra

      - name: Plan Terraform
        run: terraform plan
        working-directory: ./terraform/infra
      
      - name: Apply Terraform 
        run: terraform apply -auto-approve
        working-directory: ./terraform/infra

      

