name: CD pipeline

on:
  push:
    branches: [main]
    paths: 
      - '**/*.tf'
      - '**/*.tfvars'
      - '.github/workflows/cd.yml'
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform/infra

    steps:
      - name: Debug OIDC subject
        run: |
          echo "Repo: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::594161137006:role/oidc-github-role
          aws-region: "eu-west-3"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Format Terraform
        run: terraform fmt

      - name: Validate Terraform
        run: terraform validate

      - name: Init Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan
      
      - name: Apply Terraform 
        run: terraform apply -auto-approve

      

